# Generated by Django 4.2.1 on 2023-05-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_cita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='id_cita',
            new_name='cita',
        ),
    ]
