# Generated by Django 4.2.1 on 2023-05-17 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_id_cita_cita_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='cita',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False, verbose_name='Cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=250, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(max_length=8, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id_historiaClinica', models.AutoField(primary_key=True, serialize=False)),
                ('nombreHC', models.CharField(max_length=100, verbose_name='Nombre_Historia_Clinica')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('motivoConsulta', models.TextField(verbose_name='Motivo_de_Consulta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario')),
            ],
        ),
    ]
