# Generated by Django 4.2.1 on 2023-05-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_historiaclinica_motivoconsulta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiaclinica',
            old_name='id_historiaClinica',
            new_name='historiaClinica',
        ),
    ]
