# Generated by Django 4.2.1 on 2023-05-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_id_historiaclinica_historiaclinica_historiaclinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='cita',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Cita'),
        ),
    ]
