# Generated by Django 4.2.1 on 2023-05-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_cita_cita_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='Direccion',
            field=models.TextField(max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='nombreHC',
            field=models.TextField(max_length=100, verbose_name='Nombre Historia Clinica'),
        ),
    ]
